/******************************************************************************
*
* Name:         Change_ISO_Speed.c
* Description:  Contains function to change the speed of the ISO port using
*               the Emosyn ISO Timer values
* Copyright:    Emosyn Inc. 2005
*
* The Example Code herein below is provided "AS IS" and at your sole risk.  
* As to this Code, EMOSYN expressly disclaims all warranties, including, but
* not limited to the implied warranties of merchantability and fitness for a
* particular purpose. EMOSYN does not warrant that the functions contained in
* this code will meet your requirements, or that the operation of the code will
* be accurate, error-free, or non-infringing. No oral or written information or
* advice given by EMOSYN or an authorized representative shall create or affect
* any Warranty.
*******************************************************************************
* $Revision: 1.5 $
* $Author: amorris $ 
* $Date: 2005/10/25 12:17:36 $
******************************************************************************/


/******************************************************************************
* Header file inclusions
******************************************************************************/
#include "Firmware_API_JumpTable.h"
#include "Emosyn_Helper_Functions.h"
#include "../common/Emosyn_Clock_Speeds.h"


/******************************************************************************
* External and local function declarations 
******************************************************************************/
extern void ISO_Select_Speed (uchar FiDi, uchar ucCommand_Type);


/******************************************************************************
* External variable declarations
******************************************************************************/


/******************************************************************************
*
* Function Name:      Change_ISO_Speed
* Function Inputs:    void
* Function Outputs:   uint SW1SW2  0x0000
* Description:        Loads the ISOTMR SFR with the user input
*                     The SW1SW2 is sent before the timer change otherwise
*                     IFD may of changed its speed before chip has
*
* APDU Syntax:        E5 40 PARA1 00 00
* APDU Inputs:        PARA1  FiDi encoded baud rate
* APDU Outputs:       SW1SW2 - 9000h  Baud rate supported and changed
*                              6A86h  Baud rate not supported
*
* Example usage:      Change to ISO port speed to /372
* To Card             ->  E5 40 11 00 00
* ACK from Card       <-  40
* Response from Card  <-  90 00
*
******************************************************************************/
uint Change_ISO_Speed (void)
{
    /* Call ISO serial speed change function, passing a parameter */
    /* stating baud change was generated by APDU command */
    ISO_Select_Speed (PARA1, APDU_BAUD_CMD);

    /* Ensures the SW1SW2 is not sent out again after the speed change attempt */
    SW1SW2 = NO_SW1SW2;

    return SW1SW2;

} /* End of function */
